steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dawayir-live-agent', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dawayir-live-agent']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dawayir-live-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dawayir-live-agent'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'GOOGLE_PROJECT_ID=$PROJECT_ID,GEMINI_API_VERSION=v1alpha,GEMINI_LIVE_MODEL=models/gemini-2.5-flash-native-audio-latest'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/dawayir-live-agent'
